//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityTestClient.NARZ {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class FiverxLinkSecurityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private stackTraceElement[][] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[][] suppressed {
            get {
                return this.suppressedField;
            }
            set {
                this.suppressedField = value;
                this.RaisePropertyChanged("suppressed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class genericResponseMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeAusgabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeAusgabeDaten {
            get {
                return this.rzeAusgabeDatenField;
            }
            set {
                this.rzeAusgabeDatenField = value;
                this.RaisePropertyChanged("rzeAusgabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class einParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fiverx.de/security", ConfigurationName="NARZ.FiverxLinkSecurityService_PortType")]
    public interface FiverxLinkSecurityService_PortType {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSecurityVersion weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#rzeladeRzSecurityVersion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#rzeladeRzSecurityVersion", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionResponse ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzZertifikat weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#ladeRzZertifikat", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#ladeRzZertifikat", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatResponse ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSicherheitsmerkmale weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#ladeRzSicherheitsmerkmale", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#ladeRzSicherheitsmerkmale", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang aktiviereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#aktiviereApothekenZugang", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#aktiviereApothekenZugang", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangResponse aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verlaengereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#verlaengereApothekenZugang", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#verlaengereApothekenZugang", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangResponse verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#verarbeiteAuftrag", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityException), Action="http://fiverx.de/security#verarbeiteAuftrag", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragResponse verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.einParameterRequestMsg ladeRzSecurityVersionRequestMsg;
        
        public ladeRzSecurityVersionRequest() {
        }
        
        public ladeRzSecurityVersionRequest(FiverxLinkSecurityTestClient.NARZ.einParameterRequestMsg ladeRzSecurityVersionRequestMsg) {
            this.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSecurityVersionResponseMsg;
        
        public ladeRzSecurityVersionResponse() {
        }
        
        public ladeRzSecurityVersionResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSecurityVersionResponseMsg) {
            this.ladeRzSecurityVersionResponseMsg = ladeRzSecurityVersionResponseMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class zweiParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        private string rzeLadeRzSecurityVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rzeLadeRzSecurityVersion {
            get {
                return this.rzeLadeRzSecurityVersionField;
            }
            set {
                this.rzeLadeRzSecurityVersionField = value;
                this.RaisePropertyChanged("rzeLadeRzSecurityVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzZertifikatRequestMsg;
        
        public ladeRzZertifikatRequest() {
        }
        
        public ladeRzZertifikatRequest(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzZertifikatRequestMsg) {
            this.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzZertifikatResponseMsg;
        
        public ladeRzZertifikatResponse() {
        }
        
        public ladeRzZertifikatResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzZertifikatResponseMsg) {
            this.ladeRzZertifikatResponseMsg = ladeRzZertifikatResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg;
        
        public ladeRzSicherheitsmerkmaleRequest() {
        }
        
        public ladeRzSicherheitsmerkmaleRequest(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg) {
            this.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg;
        
        public ladeRzSicherheitsmerkmaleResponse() {
        }
        
        public ladeRzSicherheitsmerkmaleResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg) {
            this.ladeRzSicherheitsmerkmaleResponseMsg = ladeRzSicherheitsmerkmaleResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aktiviereApothekenZugangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg;
        
        public aktiviereApothekenZugangRequest() {
        }
        
        public aktiviereApothekenZugangRequest(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg) {
            this.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aktiviereApothekenZugangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg aktiviereApothekenZugangResponseMsg;
        
        public aktiviereApothekenZugangResponse() {
        }
        
        public aktiviereApothekenZugangResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg aktiviereApothekenZugangResponseMsg) {
            this.aktiviereApothekenZugangResponseMsg = aktiviereApothekenZugangResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verlaengereApothekenZugangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg;
        
        public verlaengereApothekenZugangRequest() {
        }
        
        public verlaengereApothekenZugangRequest(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg) {
            this.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verlaengereApothekenZugangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verlaengereApothekenZugangResponseMsg;
        
        public verlaengereApothekenZugangResponse() {
        }
        
        public verlaengereApothekenZugangResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verlaengereApothekenZugangResponseMsg) {
            this.verlaengereApothekenZugangResponseMsg = verlaengereApothekenZugangResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verarbeiteAuftragRequestMsg;
        
        public verarbeiteAuftragRequest() {
        }
        
        public verarbeiteAuftragRequest(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verarbeiteAuftragRequestMsg) {
            this.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verarbeiteAuftragResponseMsg;
        
        public verarbeiteAuftragResponse() {
        }
        
        public verarbeiteAuftragResponse(FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verarbeiteAuftragResponseMsg) {
            this.verarbeiteAuftragResponseMsg = verarbeiteAuftragResponseMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiverxLinkSecurityService_PortTypeChannel : FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiverxLinkSecurityService_PortTypeClient : System.ServiceModel.ClientBase<FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType>, FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType {
        
        public FiverxLinkSecurityService_PortTypeClient() {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionRequest request) {
            return base.Channel.ladeRzSecurityVersion(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZ.einParameterRequestMsg ladeRzSecurityVersionRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionRequest inValue = new FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionRequest();
            inValue.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.ladeRzSecurityVersionResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).ladeRzSecurityVersion(inValue);
            return retVal.ladeRzSecurityVersionResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatRequest request) {
            return base.Channel.ladeRzZertifikat(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzZertifikatRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatRequest inValue = new FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatRequest();
            inValue.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.ladeRzZertifikatResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).ladeRzZertifikat(inValue);
            return retVal.ladeRzZertifikatResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleRequest request) {
            return base.Channel.ladeRzSicherheitsmerkmale(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleRequest inValue = new FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleRequest();
            inValue.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.ladeRzSicherheitsmerkmaleResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).ladeRzSicherheitsmerkmale(inValue);
            return retVal.ladeRzSicherheitsmerkmaleResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangRequest request) {
            return base.Channel.aktiviereApothekenZugang(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangRequest inValue = new FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangRequest();
            inValue.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.aktiviereApothekenZugangResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).aktiviereApothekenZugang(inValue);
            return retVal.aktiviereApothekenZugangResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangRequest request) {
            return base.Channel.verlaengereApothekenZugang(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangRequest inValue = new FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangRequest();
            inValue.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.verlaengereApothekenZugangResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).verlaengereApothekenZugang(inValue);
            return retVal.verlaengereApothekenZugangResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragResponse FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType.verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragRequest request) {
            return base.Channel.verarbeiteAuftrag(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZ.genericResponseMsg verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZ.zweiParameterRequestMsg verarbeiteAuftragRequestMsg) {
            FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragRequest inValue = new FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragRequest();
            inValue.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
            FiverxLinkSecurityTestClient.NARZ.verarbeiteAuftragResponse retVal = ((FiverxLinkSecurityTestClient.NARZ.FiverxLinkSecurityService_PortType)(this)).verarbeiteAuftrag(inValue);
            return retVal.verarbeiteAuftragResponseMsg;
        }
    }
}
