//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.0.30319.17929.
// 


namespace FiverxLinkSecurityLib.Schema.V0200
{

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/V0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/V0100", IsNullable = false)]
  public partial class apoAesSchluessel
  {

    private string aesSchluesselField;

    private string aesIVField;

    private string aesEncryptionAlgorithmusField;

    /// <remarks/>
    public string aesSchluessel
    {
      get
      {
        return this.aesSchluesselField;
      }
      set
      {
        this.aesSchluesselField = value;
      }
    }

    /// <remarks/>
    public string aesIV
    {
      get
      {
        return this.aesIVField;
      }
      set
      {
        this.aesIVField = value;
      }
    }

    /// <remarks/>
    public string aesEncryptionAlgorithmus
    {
      get
      {
        return this.aesEncryptionAlgorithmusField;
      }
      set
      {
        this.aesEncryptionAlgorithmusField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://fiverx.de/security/SV0100")]
  public partial class rzSicherheitsmerkmal
  {

    private string[] encryptionAlgorithmField;

    private string[] signatureAlgorithmField;

    private string[] hashfunctionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("encryptionAlgorithm")]
    public string[] encryptionAlgorithm
    {
      get
      {
        return this.encryptionAlgorithmField;
      }
      set
      {
        this.encryptionAlgorithmField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signatureAlgorithm")]
    public string[] signatureAlgorithm
    {
      get
      {
        return this.signatureAlgorithmField;
      }
      set
      {
        this.signatureAlgorithmField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hashfunction")]
    public string[] hashfunction
    {
      get
      {
        return this.hashfunctionField;
      }
      set
      {
        this.hashfunctionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class apoInformation
  {

    private string apoIkField;

    private string rzKdNrField;

    private string apoSwHerstellerField;

    private string apoSwNameField;

    private string apoSwVersionField;

    private string apoLogMethodeField;

    private string apoInfoField;

    /// <remarks/>
    public string apoIk
    {
      get
      {
        return this.apoIkField;
      }
      set
      {
        this.apoIkField = value;
      }
    }

    /// <remarks/>
    public string rzKdNr
    {
      get
      {
        return this.rzKdNrField;
      }
      set
      {
        this.rzKdNrField = value;
      }
    }

    /// <remarks/>
    public string apoSwHersteller
    {
      get
      {
        return this.apoSwHerstellerField;
      }
      set
      {
        this.apoSwHerstellerField = value;
      }
    }

    /// <remarks/>
    public string apoSwName
    {
      get
      {
        return this.apoSwNameField;
      }
      set
      {
        this.apoSwNameField = value;
      }
    }

    /// <remarks/>
    public string apoSwVersion
    {
      get
      {
        return this.apoSwVersionField;
      }
      set
      {
        this.apoSwVersionField = value;
      }
    }

    /// <remarks/>
    public string apoLogMethode
    {
      get
      {
        return this.apoLogMethodeField;
      }
      set
      {
        this.apoLogMethodeField = value;
      }
    }

    /// <remarks/>
    public string apoInfo
    {
      get
      {
        return this.apoInfoField;
      }
      set
      {
        this.apoInfoField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAnfrage
  {

    private apoInformation apoInformationField;

    private byte[] rzDatenBoxField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzDatenBox
    {
      get
      {
        return this.rzDatenBoxField;
      }
      set
      {
        this.rzDatenBoxField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAntwort
  {

    private string hinweisField;

    private byte[] rzDatenBoxField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzDatenBox
    {
      get
      {
        return this.rzDatenBoxField;
      }
      set
      {
        this.rzDatenBoxField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzZertifikatAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzZertifikatAntwort
  {

    private string hinweisField;

    private byte[] rzZertifikatField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] rzZertifikat
    {
      get
      {
        return this.rzZertifikatField;
      }
      set
      {
        this.rzZertifikatField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAktiviereApothekenZugangAnfrage
  {

    private apoInformation apoInformationField;

    private byte[] apoAktivierungsCodeField;

    private apoAesSchluessel apoAesSchluesselField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] apoAktivierungsCode
    {
      get
      {
        return this.apoAktivierungsCodeField;
      }
      set
      {
        this.apoAktivierungsCodeField = value;
      }
    }

    /// <remarks/>
    public apoAesSchluessel apoAesSchluessel
    {
      get
      {
        return this.apoAesSchluesselField;
      }
      set
      {
        this.apoAesSchluesselField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeAktiviereApothekenZugangAntwort
  {

    private string hinweisField;

    private byte[] pkcs12KeyStoreField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] pkcs12KeyStore
    {
      get
      {
        return this.pkcs12KeyStoreField;
      }
      set
      {
        this.pkcs12KeyStoreField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeVerlaengereApothekenZugangAnfrage
  {

    private apoInformation apoInformationField;

    private string apoIkField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }

    /// <remarks/>
    public string apoIk
    {
      get
      {
        return this.apoIkField;
      }
      set
      {
        this.apoIkField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeVerlaengereApothekenZugangAntwort
  {

    private string hinweisField;

    private byte[] pkcs12KeyStoreField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] pkcs12KeyStore
    {
      get
      {
        return this.pkcs12KeyStoreField;
      }
      set
      {
        this.pkcs12KeyStoreField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSecurityVersionAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSecurityVersionAntwort
  {

    private string hinweisField;

    private string rzSecurityVersionField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    public string rzSecurityVersion
    {
      get
      {
        return this.rzSecurityVersionField;
      }
      set
      {
        this.rzSecurityVersionField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSicherheitsmerkmaleAnfrage
  {

    private apoInformation apoInformationField;

    /// <remarks/>
    public apoInformation apoInformation
    {
      get
      {
        return this.apoInformationField;
      }
      set
      {
        this.apoInformationField = value;
      }
    }
  }

  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://fiverx.de/security/SV0100")]
  [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://fiverx.de/security/SV0100", IsNullable = false)]
  public partial class rzeLadeRzSicherheitsmerkmaleAntwort
  {

    private string hinweisField;

    private rzSicherheitsmerkmal rzSicherheitsmerkmaleField;

    /// <remarks/>
    public string hinweis
    {
      get
      {
        return this.hinweisField;
      }
      set
      {
        this.hinweisField = value;
      }
    }

    /// <remarks/>
    public rzSicherheitsmerkmal rzSicherheitsmerkmale
    {
      get
      {
        return this.rzSicherheitsmerkmaleField;
      }
      set
      {
        this.rzSicherheitsmerkmaleField = value;
      }
    }
  }
}
