//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityTestClient.FiveRxSecurityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fiverx.de/security", ConfigurationName="FiveRxSecurityService.FiveRxLinkSecurityServiceSoap")]
    public interface FiveRxLinkSecurityServiceSoap {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSecurityVersion weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#rzeladeRzSecurityVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionResponse ladeRzSecurityVersion(FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzZertifikat weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#ladeRzZertifikat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatResponse ladeRzZertifikat(FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#verarbeiteAuftrag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class einParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class zweiParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        private string rzeLadeRzSecurityVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rzeLadeRzSecurityVersion {
            get {
                return this.rzeLadeRzSecurityVersionField;
            }
            set {
                this.rzeLadeRzSecurityVersionField = value;
                this.RaisePropertyChanged("rzeLadeRzSecurityVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class genericResponseMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeAusgabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeAusgabeDaten {
            get {
                return this.rzeAusgabeDatenField;
            }
            set {
                this.rzeAusgabeDatenField = value;
                this.RaisePropertyChanged("rzeAusgabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ladeRzSecurityVersionRequest", Namespace="http://fiverx.de/security", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg ladeRzSecurityVersionRequest1;
        
        public ladeRzSecurityVersionRequest() {
        }
        
        public ladeRzSecurityVersionRequest(FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg ladeRzSecurityVersionRequest1) {
            this.ladeRzSecurityVersionRequest1 = ladeRzSecurityVersionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg;
        
        public ladeRzSecurityVersionResponse() {
        }
        
        public ladeRzSecurityVersionResponse(FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg) {
            this.genericResponseMsg = genericResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg requestladeRzZertifikat;
        
        public ladeRzZertifikatRequest() {
        }
        
        public ladeRzZertifikatRequest(FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg requestladeRzZertifikat) {
            this.requestladeRzZertifikat = requestladeRzZertifikat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg;
        
        public ladeRzZertifikatResponse() {
        }
        
        public ladeRzZertifikatResponse(FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg) {
            this.genericResponseMsg = genericResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.zweiParameterRequestMsg requestAuftrag;
        
        public verarbeiteAuftragRequest() {
        }
        
        public verarbeiteAuftragRequest(FiverxLinkSecurityTestClient.FiveRxSecurityService.zweiParameterRequestMsg requestAuftrag) {
            this.requestAuftrag = requestAuftrag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg;
        
        public verarbeiteAuftragResponse() {
        }
        
        public verarbeiteAuftragResponse(FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg genericResponseMsg) {
            this.genericResponseMsg = genericResponseMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiveRxLinkSecurityServiceSoapChannel : FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiveRxLinkSecurityServiceSoapClient : System.ServiceModel.ClientBase<FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap>, FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap {
        
        public FiveRxLinkSecurityServiceSoapClient() {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiveRxLinkSecurityServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionResponse FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.ladeRzSecurityVersion(FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionRequest request) {
            return base.Channel.ladeRzSecurityVersion(request);
        }
        
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg ladeRzSecurityVersion(FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg ladeRzSecurityVersionRequest1) {
            FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionRequest inValue = new FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionRequest();
            inValue.ladeRzSecurityVersionRequest1 = ladeRzSecurityVersionRequest1;
            FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzSecurityVersionResponse retVal = ((FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).ladeRzSecurityVersion(inValue);
            return retVal.genericResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatResponse FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.ladeRzZertifikat(FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatRequest request) {
            return base.Channel.ladeRzZertifikat(request);
        }
        
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg ladeRzZertifikat(FiverxLinkSecurityTestClient.FiveRxSecurityService.einParameterRequestMsg requestladeRzZertifikat) {
            FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatRequest inValue = new FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatRequest();
            inValue.requestladeRzZertifikat = requestladeRzZertifikat;
            FiverxLinkSecurityTestClient.FiveRxSecurityService.ladeRzZertifikatResponse retVal = ((FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).ladeRzZertifikat(inValue);
            return retVal.genericResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap.verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest request) {
            return base.Channel.verarbeiteAuftrag(request);
        }
        
        public FiverxLinkSecurityTestClient.FiveRxSecurityService.genericResponseMsg verarbeiteAuftrag(FiverxLinkSecurityTestClient.FiveRxSecurityService.zweiParameterRequestMsg requestAuftrag) {
            FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest inValue = new FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragRequest();
            inValue.requestAuftrag = requestAuftrag;
            FiverxLinkSecurityTestClient.FiveRxSecurityService.verarbeiteAuftragResponse retVal = ((FiverxLinkSecurityTestClient.FiveRxSecurityService.FiveRxLinkSecurityServiceSoap)(this)).verarbeiteAuftrag(inValue);
            return retVal.genericResponseMsg;
        }
    }
}
