//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18063
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiverxLinkSecurityTestClient.NARZService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class FiverxLinkSecurityException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private stackTraceElement[] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[] suppressed {
            get {
                return this.suppressedField;
            }
            set {
                this.suppressedField = value;
                this.RaisePropertyChanged("suppressed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class genericResponseMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeAusgabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeAusgabeDaten {
            get {
                return this.rzeAusgabeDatenField;
            }
            set {
                this.rzeAusgabeDatenField = value;
                this.RaisePropertyChanged("rzeAusgabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class einParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fiverx.de/security", ConfigurationName="NARZService.FiverxLinkSecurityService_PortType")]
    public interface FiverxLinkSecurityService_PortType {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSecurityVersion weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#rzeladeRzSecurityVersion", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#rzeladeRzSecurityVersion", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionResponse ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzZertifikat weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#ladeRzZertifikat", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#ladeRzZertifikat", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatResponse ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang ladeRzSicherheitsmerkmale weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#ladeRzSicherheitsmerkmale", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#ladeRzSicherheitsmerkmale", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleResponse ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang aktiviereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#aktiviereApothekenZugang", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#aktiviereApothekenZugang", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangResponse aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verlaengereApothekenZugang weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#verlaengereApothekenZugang", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#verlaengereApothekenZugang", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangResponse verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangRequest request);
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang verarbeiteAuftrag weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="http://fiverx.de/security#verarbeiteAuftrag", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityException), Action="http://fiverx.de/security#verarbeiteAuftrag", Name="FiverxLinkSecurityException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragResponse verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.einParameterRequestMsg ladeRzSecurityVersionRequestMsg;
        
        public ladeRzSecurityVersionRequest() {
        }
        
        public ladeRzSecurityVersionRequest(FiverxLinkSecurityTestClient.NARZService.einParameterRequestMsg ladeRzSecurityVersionRequestMsg) {
            this.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSecurityVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSecurityVersionResponseMsg;
        
        public ladeRzSecurityVersionResponse() {
        }
        
        public ladeRzSecurityVersionResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSecurityVersionResponseMsg) {
            this.ladeRzSecurityVersionResponseMsg = ladeRzSecurityVersionResponseMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fiverx.de/security/types")]
    public partial class zweiParameterRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rzeEingabeDatenField;
        
        private string rzeLadeRzSecurityVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string rzeEingabeDaten {
            get {
                return this.rzeEingabeDatenField;
            }
            set {
                this.rzeEingabeDatenField = value;
                this.RaisePropertyChanged("rzeEingabeDaten");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string rzeLadeRzSecurityVersion {
            get {
                return this.rzeLadeRzSecurityVersionField;
            }
            set {
                this.rzeLadeRzSecurityVersionField = value;
                this.RaisePropertyChanged("rzeLadeRzSecurityVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzZertifikatRequestMsg;
        
        public ladeRzZertifikatRequest() {
        }
        
        public ladeRzZertifikatRequest(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzZertifikatRequestMsg) {
            this.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzZertifikatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzZertifikatResponseMsg;
        
        public ladeRzZertifikatResponse() {
        }
        
        public ladeRzZertifikatResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzZertifikatResponseMsg) {
            this.ladeRzZertifikatResponseMsg = ladeRzZertifikatResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg;
        
        public ladeRzSicherheitsmerkmaleRequest() {
        }
        
        public ladeRzSicherheitsmerkmaleRequest(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg) {
            this.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ladeRzSicherheitsmerkmaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg;
        
        public ladeRzSicherheitsmerkmaleResponse() {
        }
        
        public ladeRzSicherheitsmerkmaleResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSicherheitsmerkmaleResponseMsg) {
            this.ladeRzSicherheitsmerkmaleResponseMsg = ladeRzSicherheitsmerkmaleResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aktiviereApothekenZugangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg;
        
        public aktiviereApothekenZugangRequest() {
        }
        
        public aktiviereApothekenZugangRequest(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg) {
            this.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aktiviereApothekenZugangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg aktiviereApothekenZugangResponseMsg;
        
        public aktiviereApothekenZugangResponse() {
        }
        
        public aktiviereApothekenZugangResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg aktiviereApothekenZugangResponseMsg) {
            this.aktiviereApothekenZugangResponseMsg = aktiviereApothekenZugangResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verlaengereApothekenZugangRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg;
        
        public verlaengereApothekenZugangRequest() {
        }
        
        public verlaengereApothekenZugangRequest(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg) {
            this.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verlaengereApothekenZugangResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verlaengereApothekenZugangResponseMsg;
        
        public verlaengereApothekenZugangResponse() {
        }
        
        public verlaengereApothekenZugangResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verlaengereApothekenZugangResponseMsg) {
            this.verlaengereApothekenZugangResponseMsg = verlaengereApothekenZugangResponseMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verarbeiteAuftragRequestMsg;
        
        public verarbeiteAuftragRequest() {
        }
        
        public verarbeiteAuftragRequest(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verarbeiteAuftragRequestMsg) {
            this.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verarbeiteAuftragResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fiverx.de/security/types", Order=0)]
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verarbeiteAuftragResponseMsg;
        
        public verarbeiteAuftragResponse() {
        }
        
        public verarbeiteAuftragResponse(FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verarbeiteAuftragResponseMsg) {
            this.verarbeiteAuftragResponseMsg = verarbeiteAuftragResponseMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FiverxLinkSecurityService_PortTypeChannel : FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiverxLinkSecurityService_PortTypeClient : System.ServiceModel.ClientBase<FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType>, FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType {
        
        public FiverxLinkSecurityService_PortTypeClient() {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiverxLinkSecurityService_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionRequest request) {
            return base.Channel.ladeRzSecurityVersion(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSecurityVersion(FiverxLinkSecurityTestClient.NARZService.einParameterRequestMsg ladeRzSecurityVersionRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionRequest inValue = new FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionRequest();
            inValue.ladeRzSecurityVersionRequestMsg = ladeRzSecurityVersionRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.ladeRzSecurityVersionResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).ladeRzSecurityVersion(inValue);
            return retVal.ladeRzSecurityVersionResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatRequest request) {
            return base.Channel.ladeRzZertifikat(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzZertifikat(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzZertifikatRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatRequest inValue = new FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatRequest();
            inValue.ladeRzZertifikatRequestMsg = ladeRzZertifikatRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.ladeRzZertifikatResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).ladeRzZertifikat(inValue);
            return retVal.ladeRzZertifikatResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleRequest request) {
            return base.Channel.ladeRzSicherheitsmerkmale(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg ladeRzSicherheitsmerkmale(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg ladeRzSicherheitsmerkmaleRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleRequest inValue = new FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleRequest();
            inValue.ladeRzSicherheitsmerkmaleRequestMsg = ladeRzSicherheitsmerkmaleRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.ladeRzSicherheitsmerkmaleResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).ladeRzSicherheitsmerkmale(inValue);
            return retVal.ladeRzSicherheitsmerkmaleResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangRequest request) {
            return base.Channel.aktiviereApothekenZugang(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg aktiviereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg aktiviereApothekenZugangRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangRequest inValue = new FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangRequest();
            inValue.aktiviereApothekenZugangRequestMsg = aktiviereApothekenZugangRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.aktiviereApothekenZugangResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).aktiviereApothekenZugang(inValue);
            return retVal.aktiviereApothekenZugangResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangRequest request) {
            return base.Channel.verlaengereApothekenZugang(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verlaengereApothekenZugang(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verlaengereApothekenZugangRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangRequest inValue = new FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangRequest();
            inValue.verlaengereApothekenZugangRequestMsg = verlaengereApothekenZugangRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.verlaengereApothekenZugangResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).verlaengereApothekenZugang(inValue);
            return retVal.verlaengereApothekenZugangResponseMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragResponse FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType.verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragRequest request) {
            return base.Channel.verarbeiteAuftrag(request);
        }
        
        public FiverxLinkSecurityTestClient.NARZService.genericResponseMsg verarbeiteAuftrag(FiverxLinkSecurityTestClient.NARZService.zweiParameterRequestMsg verarbeiteAuftragRequestMsg) {
            FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragRequest inValue = new FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragRequest();
            inValue.verarbeiteAuftragRequestMsg = verarbeiteAuftragRequestMsg;
            FiverxLinkSecurityTestClient.NARZService.verarbeiteAuftragResponse retVal = ((FiverxLinkSecurityTestClient.NARZService.FiverxLinkSecurityService_PortType)(this)).verarbeiteAuftrag(inValue);
            return retVal.verarbeiteAuftragResponseMsg;
        }
    }
}
